[package]
name = "blue-client"
version = "0.1.0"
edition = "2021"

[dependencies]
bluer = { version = "0.17.3", features = ["full"] }
futures = "0.3.30"
gtk4 = "0.9.0"
gtk4-layer-shell = "0.4.0"
tokio = { version = "1.39.2", features = ["full"] }
